/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        centrarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuRegistrarCasting = new javax.swing.JMenuItem();
        menuRegistrarCliente = new javax.swing.JMenuItem();
        menuRegistrarPerfil = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        menuBuscarCasting = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        menuInformacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/LogoCasting.png"))); // NOI18N

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("Nuevo");

        menuRegistrarCasting.setMnemonic('o');
        menuRegistrarCasting.setText("Registrar Casting");
        menuRegistrarCasting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarCastingActionPerformed(evt);
            }
        });
        fileMenu.add(menuRegistrarCasting);

        menuRegistrarCliente.setMnemonic('s');
        menuRegistrarCliente.setText("Registrar Cliente");
        menuRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarClienteActionPerformed(evt);
            }
        });
        fileMenu.add(menuRegistrarCliente);

        menuRegistrarPerfil.setMnemonic('a');
        menuRegistrarPerfil.setText("Registrar Perfil");
        menuRegistrarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarPerfilActionPerformed(evt);
            }
        });
        fileMenu.add(menuRegistrarPerfil);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Buscar");

        menuBuscarCasting.setMnemonic('t');
        menuBuscarCasting.setText("Buscar Casting");
        menuBuscarCasting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarCastingActionPerformed(evt);
            }
        });
        editMenu.add(menuBuscarCasting);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        menuInformacion.setMnemonic('c');
        menuInformacion.setText("Información");
        menuInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInformacionActionPerformed(evt);
            }
        });
        helpMenu.add(menuInformacion);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(btnSalir)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInformacionActionPerformed
       JOptionPane.showMessageDialog(this, "Este proyecto fue realizado por \nAlexandra Iveth Rodriguez Castellanos - 229949\nIsaac Castelo Valenzuela - 216823\nSaul Armando Reyna Lopez - 229256\nDiseño de Software", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuInformacionActionPerformed

    private void menuRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarClienteActionPerformed
        FrmRegistrarCliente frmRegcliente = new FrmRegistrarCliente();
        frmRegcliente.setVisible(true);  
    }//GEN-LAST:event_menuRegistrarClienteActionPerformed

    private void menuRegistrarCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarCastingActionPerformed
        FrmRegistrarCasting frmRegCasting = new FrmRegistrarCasting();
        frmRegCasting.setVisible(true);
    }//GEN-LAST:event_menuRegistrarCastingActionPerformed

    private void menuRegistrarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarPerfilActionPerformed
        FrmRegistrarPerfil frmRegPerfil = new FrmRegistrarPerfil();
        frmRegPerfil.setVisible(true);

    }//GEN-LAST:event_menuRegistrarPerfilActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void menuBuscarCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarCastingActionPerformed
        FrmBuscarCasting frmBuscarCasting = new FrmBuscarCasting();
        frmBuscarCasting.setVisible(true);
    }//GEN-LAST:event_menuBuscarCastingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    
    
   private void centrarVentana() {
        Dimension screenSize, frameSize;
        int x, y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize = getSize();
        x = (screenSize.width - frameSize.width) / 2;
        y = (screenSize.height - frameSize.height) / 2;
        setLocation(x, y);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBuscarCasting;
    private javax.swing.JMenuItem menuInformacion;
    private javax.swing.JMenuItem menuRegistrarCasting;
    private javax.swing.JMenuItem menuRegistrarCliente;
    private javax.swing.JMenuItem menuRegistrarPerfil;
    // End of variables declaration//GEN-END:variables

}
